command:
  - "hypercorn"
  - "app:app"
  - "--bind"
  - "127.0.0.1:8000"

env:
  - name: "SERVING_ENDPOINT_NAME"
    value: "databricks-meta-llama-3-3-70b-instruct"
  - name: "DATABRICKS_TOKEN"
    valueFrom: "databricks-token"